services:
  app:
    build: .
    image: app

    volumes:
      - ./:/var/www/html

    ports:
      - "8080:80"

  db:
    image: postgres:16-alpine
    shm_size: 128mb

    volumes:
      - /var/lib/postgresql/data

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}